- name: creating folder
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/folder.xml') }}"
    name: "{{dir}}"
    password: "{{jenkins_password}}"
    url: http://172.31.32.41:8080
    user: admin

- name: including the piple line task
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - frontend
    - catalogue
    - user
    - cart
    - shipping
    - payment
    - dispatch