- name: copying the xml file
  ansible.builtin.template:
    src: config.xml
    dest: /tmp/{{item}}.xml
- name: creating jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "{{item}}"
    password: "{{jenkins_password}}"
    url: http://172.31.32.182:8080
    user: admin