- name: creating jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/job.xml') }}"
    name: "{{item}}"
    password: "{{jenkins_password}}"
    url: http://172.31.45.34:8080
    user: admin