- name: creating jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/job.xml') }}"
    name: "{{dir}}/{{item}}"
    password: "{{jenkins_password}}"
    url: http://172.31.32.41:8080
    user: admin